"""Exact diff of two tzdb releases over future instants.

Offsets can only change at (a) explicit TZif transitions or (b) instants
generated by the POSIX footer rule. Enumerating the union of both zones'
boundaries and comparing offsets on each resulting interval is exact — no
sampling, so a change cannot be stepped over.
"""

from __future__ import annotations

import datetime as dt
from dataclasses import dataclass, asdict, field

from . import releases, tzif


@dataclass(frozen=True)
class Unparseable:
    """A zone present in both releases that could not be compared.

    Surfaced, never dropped: a diff that silently skips a zone reports
    "no change" for rows in that zone, which is the one answer this tool
    must never give by accident (before this class existed, Asia/Tehran
    vanished from every 2020a-2022a diff without a trace).
    """

    zone: str
    error: str

    def as_dict(self) -> dict:
        return asdict(self)


@dataclass
class DiffResult:
    """Deliberately not iterable and not truthy: callers must read ``.changes``
    and ``.unparseable`` explicitly, so an incomplete result can never look
    like an empty one."""

    changes: list[Change] = field(default_factory=list)
    unparseable: list[Unparseable] = field(default_factory=list)

    @property
    def complete(self) -> bool:
        return not self.unparseable


@dataclass(frozen=True)
class Change:
    zone: str
    start_utc: int
    end_utc: int | None  # None = still differing at the end of the window
    old_offset: int
    new_offset: int

    @property
    def shift_seconds(self) -> int:
        return self.new_offset - self.old_offset

    def as_dict(self) -> dict:
        d = asdict(self)
        d["start"] = dt.datetime.fromtimestamp(self.start_utc, dt.timezone.utc).isoformat()
        d["end"] = (
            dt.datetime.fromtimestamp(self.end_utc, dt.timezone.utc).isoformat()
            if self.end_utc is not None
            else None
        )
        d["shift_seconds"] = self.shift_seconds
        return d


def diff_zone(a: tzif.Tz, b: tzif.Tz, zone: str, start: int, end: int) -> list[Change]:
    points = sorted({start} | set(a.boundaries(start, end)) | set(b.boundaries(start, end)))
    changes: list[Change] = []
    open_run: tuple[int, int, int] | None = None  # (start, old, new)
    for i, p in enumerate(points):
        oa, ob = a.offset_at(p), b.offset_at(p)
        if oa != ob:
            if open_run is None or open_run[1] != oa or open_run[2] != ob:
                if open_run is not None:
                    changes.append(Change(zone, open_run[0], p, open_run[1], open_run[2]))
                open_run = (p, oa, ob)
        elif open_run is not None:
            changes.append(Change(zone, open_run[0], p, open_run[1], open_run[2]))
            open_run = None
    if open_run is not None:
        changes.append(Change(zone, open_run[0], None, open_run[1], open_run[2]))
    return changes


def diff(
    from_version: str,
    to_version: str,
    start: dt.datetime | None = None,
    years: int = 10,
) -> DiffResult:
    """Compare every zone present in both releases over [start, start + years).

    A zone that cannot be read in either release is *not* skipped: it is
    returned in ``DiffResult.unparseable`` so the caller can refuse to call the
    result complete. There is deliberately no path that drops a zone.
    """
    za, zb = releases.compile(from_version), releases.compile(to_version)
    start_dt = start or dt.datetime.now(dt.timezone.utc)
    s = int(start_dt.timestamp())
    e = int((start_dt + dt.timedelta(days=365 * years)).timestamp())
    common = sorted(releases.zones(za) & releases.zones(zb))
    result = DiffResult()
    for z in common:
        try:
            ta, tb = tzif.read(str(za / z)), tzif.read(str(zb / z))
        except Exception as exc:  # recorded, never dropped
            result.unparseable.append(Unparseable(z, f"{type(exc).__name__}: {exc}"))
            continue
        result.changes.extend(diff_zone(ta, tb, z, s, e))
    return result
